# camera:
#   - id: cam_1
#     source: 0  
#   - id: cam_2
#     source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"
camera:
  - id: cam_1
    source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_2
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_3
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_4
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_5
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_6
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_7
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_8
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_9
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_10
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_11
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_12
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_13
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_14
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_15
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_16
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_17
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_18
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_19
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_20
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_21
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_22
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_23
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_24
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

  # - id: cam_25
  #   source: "rtsp://admin:diffuse123@192.168.0.183:554/cam/realmonitor?channel=1&subtype=0"

yolo:
  model_path: models/yolo/best.engine
  conf_threshold: 0.7

vlm:
  model_path: models/Qwen3-VL-2B-Instruct
  max_new_tokens: 5
  prompt: |
    You are a fire detection system.

    Analyze the image carefully.

    Rules:
    - Only return ONE word
    - Valid answers: FIRE, SMOKE, NONE
    - Do not explain
    - Be strict (avoid false positives)

    Answer:
  use_fp16: true
  device: cuda
  valid_labels: ["FIRE", "SMOKE"]
  
ui:
  window_width: 1280
  window_height: 720

  font_scale: 1.0
  font_thickness: 3

  bbox_thickness: 4

  show_label: true
  show_warning: true

alerts:
  save_dir: alerts
  vlm_confirm_dir: alerts/vlm_confirm

system:
  cooldown: 2
  resize: [160, 160]
  sleep: 0.01